locals {
  project_name                       = "monolithic-app"
  environment                        = "dev"
  app_vpc_name                       = "${local.project_name}-app-vpc"
  cicd_vpc_name                      = "${local.project_name}-cicd-vpc"
  public_subnet_app_name             = "${local.project_name}-public-subnet-app"
  private_subnet_app_1_name          = "${local.project_name}-private-subnet-app-1"
  private_subnet_app_2_name          = "${local.project_name}-private-subnet-app-2"
  private_subnet_app_3_name          = "${local.project_name}-private-subnet-app-3"
  private_subnet_app_4_name          = "${local.project_name}-private-subnet-app-4"
  public_subnet_cicd_name            = "${local.project_name}-public-subnet-cicd"
  internet_gateway_name              = "${local.project_name}-internet-gateway"
  public_route_table_name            = "${local.project_name}-public-route-table"
  nat_gateway_name                   = "${local.project_name}-nat-gateway"
  eip_name                           = "${local.project_name}-eip"
  private_route_table_name           = "${local.project_name}-private-route-table"
  backend_security_group_name        = "${local.project_name}-backend-security-group"
  app_lb_name                        = "${local.project_name}-app-lb"
  loadbalancer_security_group_name   = "${local.project_name}-loadbalancer-security-group"
  frontend_security_group_name       = "${local.project_name}-frontend-security-group"
  database_security_group_name       = "${local.project_name}-database-security-group"
  loadbalancer_target_group_frontend = "${local.project_name}-target-group-frontend"
  loadbalancer_target_group_backend  = "${local.project_name}-target-group-backend"
  database_name                      = "app-database"
}
